MediBird/caring-note-web

.github/workflows/send-docker-image.yml

ci: docker hub 경로 변경

---

src/app/App.tsx
src/app/Router.tsx
src/app/Routes.tsx
src/main.tsx
src/pages/assistant/AssistantBasicInfo.tsx
src/pages/assistant/AssistantHealthInfo.tsx
src/pages/assistant/AssistantHome.tsx
src/pages/assistant/AssistantLifeInfo.tsx

1. fix(modules): 🐛 react-modal 추가
2. fix(공통): 🐛 main 수정
3. feat(공통): ✨ 라우터 파일 분리 App -> Router -> Routers
4. feat(기초상담화면): ✨ 라우터 & 기본 화면 설정

feat: ✨  separate router and add basic router 

---

hooks.ts
src/app/App.tsx
src/app/Router.tsx
src/app/Routes.tsx
src/components/Badge.tsx
src/components/Button.tsx
src/components/NavigationLeft.tsx
src/components/NavigationLeftMenu.tsx
src/components/NavigationRight.tsx
src/components/Tooltip.tsx
src/components/common/InputComponent.tsx
src/components/consult/HighlightInput.tsx
src/main.tsx
src/pages/Root.tsx
src/pages/assistant/AssistantHealthInfo.tsx
src/pages/assistant/AssistantHome.tsx
src/pages/assistant/AssistantLifeInfo.tsx
src/pages/consult/Consult.tsx
src/pages/consult/ConsultCard.tsx
src/pages/consult/DiscardMedicine.tsx
src/pages/consult/MedicineConsult.tsx
src/pages/consult/MedicineMemo.tsx
src/pages/consult/PastConsult.tsx
src/reducers/editorStateReducer.ts
src/reducers/navigationReducer.ts
src/reducers/store.ts
src/reducers/tabReducer.ts
tsconfig.json
tsconfig.node.json
vite.config.ts

fix(절대경로): 🐛 절대경로 수정

---

hooks.ts
src/app/App.tsx
src/app/Router.tsx
src/app/Routes.tsx
src/components/Badge.tsx
src/components/Button.tsx
src/components/NavigationLeft.tsx
src/components/NavigationLeftMenu.tsx
src/components/NavigationRight.tsx
src/components/Tooltip.tsx
src/components/common/InputComponent.tsx
src/components/consult/HighlightInput.tsx
src/main.tsx
src/pages/Root.tsx
src/pages/assistant/AssistantHealthInfo.tsx
src/pages/assistant/AssistantHome.tsx
src/pages/assistant/AssistantLifeInfo.tsx
src/pages/consult/Consult.tsx
src/pages/consult/ConsultCard.tsx
src/pages/consult/DiscardMedicine.tsx
src/pages/consult/MedicineConsult.tsx
src/pages/consult/MedicineMemo.tsx
src/pages/consult/PastConsult.tsx
src/reducers/editorStateReducer.ts
src/reducers/navigationReducer.ts
src/reducers/tabReducer.ts
store.ts
tsconfig.json
tsconfig.node.json
vite.config.ts

This reverts commit 9b19432581a06e58ecd8e2d510a38c2ef9f453c0.

Revert "fix(절대경로): 🐛 절대경로 수정 (#22)"

---

package-lock.json
package.json
src/components/Button.tsx
src/components/common/TableComponent.tsx
src/components/consult/HighlightInput.tsx
src/pages/consult/DiscardMedicine.tsx
src/pages/consult/MedicineMemo.tsx
src/pages/consult/PastConsult.tsx
src/utils/TableUtils.tsx
tsconfig.json
vite.config.ts

- 테이블 컴포넌트 리팩토링 포함
- momentJS 도입 (날짜 포맷 라이브러리, 안써보셨다면 이거 추천드려요)
- 이전 상담 내역 탭 테이블 개발 완료
- 다른 테이블들은 기능 검증 후 마무리 개발 예정
- 홈화면 테이블 또한 기획 수정중이므로 보류

Feature: 이전 상담 내역 탭 테이블 반영

---

src/components/NavigationRight.tsx

- color set 적용
- svg 변환은 33 PR 승인 후 진행

refactor: :recycle: color set 적용

---

src/components/NavigationRight.tsx

전일 빌드 버그 픽스 하는 과정에서 배지 아이콘을 빼지 못했네요 :(

우측 네비게이션 녹음중 배지 아이콘 제거

---

src/components/common/CardContainer.tsx
src/components/common/CardContent.tsx
src/components/common/HistoryList.tsx
src/components/consult/GradationContainer.tsx
src/components/consult/TabContentTitle.tsx
src/pages/assistant/AssistantBasicInfo.tsx
src/pages/consult/Consult.tsx
src/pages/consult/ConsultCard.tsx
src/pages/consult/PastConsult.tsx
tailwind.config.js

주말을 불태워서 브랜치가 살짝 무겁습니다...
- 본상담화면 상단 공통영역 리팩토링
- 이전상담내역, 상담카드 화면 완료
- 컴포넌트화 완료

feat: complete consultant page

---

package.json
pnpm-lock.yaml
src/components/components/ui/dialog.tsx
src/pages/Home.tsx

Dialog컴포넌트 tailwind.config.js global css 적용

fix: 🐛 Dialog컴포넌트 tailwind.config.js global css 적용

---

src/components/components/ui/checkbox.tsx
src/components/components/ui/radio-group.tsx
src/pages/assistant/AssistantBasicInfo.tsx
src/pages/assistant/AssistantHealthInfo.tsx
src/pages/assistant/AssistantHome.tsx
src/pages/assistant/AssistantLifeInfo.tsx

1. 기본 정보 탭 개발
2. 건강 정보 탭 개발
3. 생활 정보 탭 개발

feat: ✨ 상담 카드 작성 1차 개발

---

src/pages/consult/Consult.tsx
src/pages/consult/PastConsult.tsx

feat: ✨ 이전 상담 내역 탭 API 연동 완료

---

src/components/common/TableComponent.tsx

test: :construction: 기디쪽 기능확인을 위해 테이블 컴포넌트 컬럼 기능 풀기

---

src/app/Routes.tsx
src/pages/assistant/AssistantBasicInfo.tsx
src/pages/assistant/AssistantHealthInfo.tsx
src/pages/assistant/AssistantHome.tsx
src/pages/assistant/AssistantLifeInfo.tsx
src/pages/assistant/AssistantView.tsx

1. fix: 🐛 assistantRoutes 에서 path 변경
2. fix: 🐛 AssistnatHome tabTitle url 변경
3. fix: 🐛 dispatch url 변경
4. fix: 🐛 동의하기 누를 경우 navigate url 변경

fix: 🐛 assistant view url 변경

---

src/components/components/ui/dialog.tsx
src/pages/assistant/AgreementDetails2Dialog.tsx
src/pages/assistant/AgreementDetails3Dialog.tsx
src/pages/assistant/AgreementDetailsDialog.tsx
src/pages/assistant/AssistantView.tsx

1. fix: 🐛 DialogCloseButton 컴포넌트 밖으로 빼기
2. fix: 🐛 개인정보 수집 * 이용 내역 동의 체크박스 삭제
3. fix: 🐛 개인정보의 제 3자 제공 동의 체크박스 삭제
4. fix: 🐛 폐의약품 수거에 관한 동의 체크박스 삭제

fix: 🐛 개인정보 수집 동의서 작성 Dialog 수정

---

src/app/Routes.tsx
src/pages/assistant/AssistantHome.tsx
src/pages/assistant/AssistantIndependentInfo.tsx

1. feat: ✨ tabTitle에 자립생활 역량 메뉴 추가
2. feat: ✨ assistantRoutes에 자립생활 역량 페이지 추가

feat: ✨ 자립생활 역량 페이지 개발

---

src/hooks/useCounselSessionQuery.ts
src/pages/assistant/AssistantView.tsx
src/store/counselSessionStore.ts
tsconfig.json
vite.config.ts

1. feat: ✨ hooks 절대경로 설정
2. feat: ✨ react-query 활용 api 호출 함수 생성
3. feat: ✨ Zustand로 useCounselSessionStore 생성
4. feat: ✨ react-query & zustand 활용 상담일정 목록 조회 페이지 적용

 feat: ✨ react-query & zustand 활용 상담일정 목록 조회

---

src/components/ui/datepicker.tsx
src/pages/Consult/components/tabs/MedicineMemo.tsx

- 테이블에 DatePicker 추가
- DatePicker 컴포넌트 리팩토링

feat: :sparkles: add date picker to table component

---

src/hooks/useCounselAgreeQuery.ts
src/hooks/useCounselSessionQuery.ts
src/pages/assistant/Assistant.tsx
src/pages/assistant/dialogs/Index.tsx
src/store/counselSessionStore.ts

1. feat: ✨ react-query활용 내담자 개인정보 수집 동의 여부 조회 & 등록 API 설정
2. fix: 🐛 상담 일정 목록 조회 API 에서 baseDate 필수값 수정
3. fix: 🐛 내담자 개인정보 수집 동의 여부 조회 API 연결 & ENUM 값 설정
4. refactor: ♻ 내담자 개인정보 수집 동의 여부 등록 API 연결 & mainDialog 파일 분리
5. fix: ✨ zustand 활용 CounselSession에 대한 DetailState 값 설정

feat: ✨ Assistant 화면 API 연동

---

src/components/consult/HighlightInput.tsx
src/hooks/useMedicineConsultQuery.ts
src/pages/Consult/components/tabs/MedicineConsult.tsx
src/store/medicineConsultStore.ts
src/types/MedicineConsultDTO.ts

using react-query for API Call
using zustand for MedicineConsultDTO State 
using redux for  EditorState

Feature: medicine consult data fetch

---

src/hooks/useMedicineConsultQuery.ts

refactor: remove counselNeedStatus

refactor :  remove useless value in useMedicineConsultQuery

---

src/components/ui/buttonVariants.ts
src/pages/assistant/tabs/BasicInfo.tsx
src/pages/assistant/tabs/HealthInfo.tsx
src/pages/assistant/tabs/IndependentInfo.tsx
src/pages/assistant/tabs/LifeInfo.tsx

1. feat: ✨ pressed 와 nonpressed 속성 buttonVariants에 추가
2. refactor: ♻ buttonVariants속성 추가에 따른 상담카드 작성 Button 수정

feat: ✨  버튼 컴포넌트 buttonVariants 속성 추가

---

src/pages/assistant/AssistantInfo.tsx
src/pages/assistant/tabs/BaseInfo.tsx
src/pages/assistant/tabs/HealthInfo.tsx
src/pages/assistant/tabs/IndependentInfo.tsx
src/pages/assistant/tabs/LifeInfo.tsx

1. refactor: ♻ BasicInfo -> BaseInfo 파일 이름 변경
2. refactor: ♻ 간격 조정 & history icon 제거
3. refactor: ♻ 동의여부 수정 버튼 제거
4. refactor: ♻ 상담 카드 작성 -> 기초 설문 작성 네이밍 변경

refactor: ♻️ 상담카드 작성 화면 퍼블리싱 수정

---

src/api/api.ts
src/components/ui/datepicker.tsx
src/components/ui/timepicker.tsx
src/pages/Consult/components/tabs/MedicineMemo.tsx
src/pages/Counselee/constants/dialog/index.ts
src/pages/Counselee/dialogs/ItemChange.tsx
src/pages/Counselee/hooks/query/useCounseleeInfoQuery.tsx
src/pages/Counselee/index.tsx

[ 공통 컴포넌트 ] 
1. datepicker 원복 & 의약물 기록 수정
2. Timepicker 컴포넌트 추가
[ 내담자 관리 페이지 ]
1. 리스트 삭제 -> 선택 삭제로 변경
2. 장애여부 & 전화번호 리스트 표시 수정
3. 내담자 기본 정보 삭제 수정

refactor: ♻ 내담자 기본 정보 페이지 수정

---

src/pages/Consult/components/table/WasteMedicationTable.tsx
tailwind.config.js

https://www.notion.so/yoonyounglee/UI-7f8b46a9f1b740fdbc62f53c0115241c?pvs=4
- tailwind config 수정
- badge 공통 컴포넌트 사용

fix(QA): :bug: 뱃지 UI 수정 필요함

---

src/pages/Survey/dialogs/userInfo/InformationThirdParties.tsx
src/pages/Survey/tabs/BaseInfo.tsx
src/pages/Survey/tabs/Index.tsx

1. fix: 🐛 초기 상담 설문 작성시 문구 '이전~'비활성화
2. fix: 🐛 초기 상담 설문 작성시 빈값으로 초기화

fix: 🐛 초기 상담 설문 페이지 수정 Ver1.1

---

package.json
pnpm-lock.yaml
src/components/NavigationLeft.tsx
src/components/NavigationRight.tsx
src/components/common/CardContainer.tsx
src/components/common/DataTable/DataTable.tsx
src/components/common/DataTable/MedicineSearchCell.tsx
src/components/common/DataTable/SelectCell.tsx
src/components/common/DataTable/SelectCellWithCustomInput.tsx
src/components/common/DataTable/TextInputCell.tsx
src/components/ui/card.tsx
src/components/ui/command.tsx
src/components/ui/datepicker.tsx
src/components/ui/dropdown-menu.tsx
src/components/ui/input.tsx
src/components/ui/popover.tsx
src/components/ui/select.tsx
src/components/ui/table.tsx
src/components/ui/tabs.tsx
src/hooks/useDebounce.tsx
src/pages/Consult/components/table/WasteMedicationTable.tsx
src/pages/Consult/components/table/WasteMedicationTableLegacy.tsx
src/pages/Consult/components/table/wasteMedicationColums.tsx
src/pages/Consult/components/tabs/DiscardMedicine.tsx
src/pages/Consult/hooks/query/useSaveWasteMedication.ts
src/pages/Consult/index.tsx
src/pages/Home/index.tsx
tailwind.config.js

- shadcn, tanstack table 활용 datatable 컴포넌트 추가
- cell edit 컴포넌트 구현
- input
- select
- select with custom input
- 의약품 검색
- 폐의약품 목록 테이블 마이그레이션 적용
- legacy mui 테이블 유지
- 기타 스타일 수정

refactor: shadcn datatable 추가 및 폐의약품 테이블 마이그레이션

---

package.json
pnpm-lock.yaml
src/api/base.ts
src/api/errorHandler.ts
src/app/App.tsx
src/components/common/DataTable/table-filter.tsx
src/components/ui/sonner.tsx
src/context/AuthContext.tsx
src/pages/Counselee/components/CounseleeTableSection.tsx
src/pages/Counselee/components/SearchInput.tsx
src/pages/Counselee/components/dialog/CounseleeDialog.tsx
src/pages/Counselee/components/table/CounseleeTable.tsx
src/pages/Counselee/components/table/counseleeColumns.tsx
src/pages/Counselee/hooks/query/useCounseleeManagement.ts
src/pages/Counselee/hooks/store/counseleeInfoStore.ts
src/pages/Counselee/index.tsx

Sonner 추가
Table filter 변경
생년월일 표시 형식 변경
https://www.notion.so/1a34b68481fb8009b538ce13dc270d20?pvs=5

fix: 💄 fix UI stuffs (qa-counselee management)

---

src/components/common/DataTable/data-table.tsx
src/components/ui/tabs.tsx
src/pages/Consult/index.tsx
src/pages/Counselee/components/Header.tsx
src/pages/Counselee/components/table/CounseleeTable.tsx
src/pages/Counselee/components/table/counseleeColumns.tsx
src/pages/Counselee/hooks/store/counseleeInfoStore.ts
src/pages/Counselee/index.tsx
src/pages/Counselee/layout/CounseleeManagementLayout.tsx
tailwind.config.js

- 내담자관리 페이지 레이아웃 수정
- content max width tailwind config 추가 및 적용

refactor: 내담자관리 페이지 라이아웃 수정

---

src/components/common/DataTable/data-table.tsx
src/components/ui/table.tsx
src/pages/Counselee/components/table/CounseleeTable.tsx

- 테이블 overflow 중복선언 제거
- 스크롤 track 영역 overflow 방지를 위한 border 스타일링 요소 테이블 컨테이너로 변경

refactor: :art: 테이블 가로스크롤 중복 제거, border 적용 요소 변경

---

.github/workflows/d-day-auto-labeler.yml
src/components/common/DataTable/table-filter.tsx

테이블 필터에서 필터 초기화까지 스크롤에 포함되는 현상을 해결하려고 했습니다.
테이블필터를 커맨드 리스트에서 분리했습니다.
오토 라벨링 시에 D-N이 인식되지 않는 오류를 해결했습니다.
```
```
---

refactor: :lipstick: refactor table-filter

---

src/pages/Home/components/ConsultCount.tsx

… readability
-  메인페이지 이미지 사이즈 지정
-  메인페이지 이미지 사이즈 지정
- 없음
-
```
```
---

refactor: :art 메인페이지 이미지 사이즈 지정

---

src/api/errorHandler.ts
src/app/Routes.tsx

- 권한 없음 처리
- 포비든 페이지 리다이렉트
-
-
```
```
---

feat: :sparkles: add forbidden page

---

src/api/api/counsel-card-controller-api.ts
src/api/api/default-api.ts
src/api/models/drinking-dto.ts
src/api/models/smoking-dto.ts
src/components/common/NavigationLeft.tsx
src/components/ui/time-picker.tsx
src/pages/Account/components/dialog/AccountDetailDialog.tsx
src/pages/Account/components/dialog/BasicInfoTab.tsx
src/pages/Account/components/table/CounselorColumns.tsx
src/pages/Consult/components/tabs/ConsultCard.tsx
src/pages/Survey/components/tabs/LivingInfo.tsx
src/pages/Survey/consent.tsx
src/pages/Survey/hooks/counselCardStore.ts
src/pages/Survey/hooks/useCounselCardQuery.ts
src/utils/constants.ts

- [https://www.notion.so/yoonyounglee/UI-1b94b68481fb80d2b743c620562f50fb?pvs=4](상담 목적 및 특이사항 부분 UI 상이)
- [https://www.notion.so/yoonyounglee/1b94b68481fb80adb6e1fae637571e4b?pvs=4] (기초 상담 내역 → 기초 설문 워딩 변경)
- [https://www.notion.so/yoonyounglee/1b94b68481fb80d5aec6d8cd36f237ac?pvs=4] (기초설문 설문완료 시 오류가 뜸)
- [https://www.notion.so/yoonyounglee/1b94b68481fb80448882d346a0467758?pvs=4] (알레르기여부, 부작용여부 클릭 불가)
- [https://www.notion.so/yoonyounglee/1b94b68481fb80ce9206f1fa2109ca2b?pvs=4] (상담 목적 셀렉트버튼 > 선택 해제되지 않음)
- [https://www.notion.so/yoonyounglee/1b94b68481fb8096ac38ef68f44cc04c?pvs=4] (흡연, 음주 선택해도 하위 항목 노출되지 않음)
- 기초 상담 api와 모델 변경되었습니다.
- sonner toast validation 추가되었습니다.
- 기초상담의 onChange function들에 수정이 있었습니다.
- 흡연/음주 선택 값 추가 되었습니다
- 유저 권한에 대한 enum constant.ts에 추가했습니다.
알려지지 않았던 버그 -> 기초 상담 …

fix: resolve qa errors

---

src/components/ui/time-picker.tsx
src/pages/Survey/components/tabs/BasicInfo.tsx
src/pages/Survey/components/tabs/HealthInfo.tsx
src/pages/Survey/hooks/useCounselCardQuery.ts

- (#181 )에서 누락한 변경사항 반영
- 린트 에러 해결
- time-picker에서 계속 default time으로 적용되어서 저장되어버리는 현상 수정

fix: :bug: fix time-picker and lint errors

---

src/components/NavigationRight.tsx
src/components/consult/HighlightInput.tsx
src/pages/Consult/components/FinishConsultDialog.tsx
src/pages/Consult/components/TemporarySaveDialog.tsx

- STT 관련 QA 대응
- 임시저장 Dialog 조건 변경 / SNB Highlight input 반응형 기능 추가
- 없음
- 없음
```
```
---

fix(QA): 🐛 STT 관련 QA 대응

---

src/components/common/NavigationLeft.tsx
src/components/ui/calendar.tsx
src/components/ui/datepicker.tsx
src/pages/Home/components/AssignDialog.tsx
src/pages/Home/components/TodayScheduleTable/todayScheduleTableColumn.tsx
src/pages/Home/index.tsx

담당약사가 지정 안됐을 때 UI 수정 필요
[https://www.notion.so/yoonyounglee/UI-1b94b68481fb8017924bd640a6713f3b?pvs=4](https://www.notion.so/1b94b68481fb8017924bd640a6713f3b?pvs=21)
1월 달력이 모두 clickable한데 선택하면 번쩍 거리는 현상
[https://www.notion.so/yoonyounglee/1-clickable-1b94b68481fb80598ae9ee945196add9?pvs=4](https://www.notion.so/1b94b68481fb80598ae9ee945196add9?pvs=21)
담당약사가 지정 안됐을 때 상담 할당 버튼 수정 필요
[https://www.notion.so/yoonyounglee/1b94b68481fb8049a703fadcb670969f?pvs=4](https://www.notion.so/1b94b68481fb8049a703fadcb670969f?pvs=21)
-
-
-
```
- Review는 특수한 케이스가 아니면 Reviewer로 지정된 …
```

refactpr: 홈 QA 반영

---

src/pages/Consult/index.tsx
src/pages/Home/index.tsx

- SNB 버그 수정
- Home.tsx 에서 우측 SNB 를 접어두고  sessionItem 에 auto 펼침 flag 를 set 합니다
- 없음
- 없음
```
```
---

fix: :bug: STT 완료된 상담 진입 시 항상 SNB 가 펼쳐지는 버그 수정

---

src/api/errorHandler.ts
src/components/common/DataTable/data-table.tsx
src/components/consult/HighlightInput.tsx
src/components/ui/buttonVariants.ts
src/components/ui/costom-toast.tsx
src/components/ui/datepicker.tsx
src/components/ui/sonner.tsx
src/components/ui/table.tsx
src/components/ui/time-picker.tsx
src/hooks/useCounselSessionQuery.ts
src/pages/Account/components/dialog/AccountDetailDialog.tsx
src/pages/Account/components/dialog/BasicInfoTab.tsx
src/pages/Account/components/dialog/PasswordChangeTab.tsx
src/pages/Consult/components/tabs/MedicineConsult.tsx
src/pages/Consult/hooks/query/medicationRecord/useMedicationRecordSave.tsx
src/pages/Consult/hooks/query/wasteMedicineRecord/useSaveWasteMedication.ts
src/pages/Consult/hooks/query/wasteMedicineRecord/useWasteMedicationMutate.tsx
src/pages/Consult/index.tsx
src/pages/Session/components/CounselSessionTableSection.tsx
src/pages/Session/components/dialog/CounseleeSearchInput.tsx
src/pages/Session/components/dialog/CreateReservationDialog.tsx
src/pages/Session/components/dialog/EditReservationDialog.tsx
src/pages/Session/components/table/CounselSessionTable.tsx
src/pages/Survey/index.tsx

- QA Resolve
임시저장 시 토스트 노출되도록 수정
[https://www.notion.so/yoonyounglee/952c2ec400b94c3087e2f5e618625f6b?pvs=4](https://www.notion.so/952c2ec400b94c3087e2f5e618625f6b?pvs=21)
폐의약물 기록 → 폐의약품 처리 워딩 변경
[https://www.notion.so/yoonyounglee/1ba4b68481fb805592aff9db1e93791a?pvs=4](https://www.notion.so/1ba4b68481fb805592aff9db1e93791a?pvs=21)
버튼 디자인필터링
[https://www.notion.so/yoonyounglee/1b94b68481fb80208137d0444be0ef6d?pvs=4](https://www.notion.so/1b94b68481fb80208137d0444be0ef6d?pvs=21)
상담 등록 오류
[https://www.notion.so/yoonyounglee/1b14b68481fb806e8d72de2b865760f5?pvs=4](https://www.notion.so/1b14b68481fb806e8d72de2b865760f5?pvs=21)
상담 일정 유저 액션 노티 부재
[https://www.notion.so/yoonyounglee/1b14b68481fb803c9482db036ae56a64?pvs=4](https://www.notion.so/1b14b68481fb803c9482db036ae56a64?pvs=21)
> 없으면 "없음" …

feat: toast등 저장 동작 QA 반영

---

src/api/errorHandler.ts
src/app/Routes.tsx

- api가 아니라 web에서 라우팅의 주도권을 가져가려고 합니다.
- 에러 핸들러 라우팅을 라우터에서 protected route라는 개념으로 바꿨습니다.
- 없음
- 이렇게 선언하는 것이 나을지..? 아니면 더 좋은 방법이 있을지
```
```
---

feat: :passport_control: refactor router by roles

---

src/pages/Session/components/table/CounselSessionTable.tsx
src/pages/Survey/index.tsx

- 세션 관리 row click 지원
- 기초 상담 완료시 이전으로 이동
-
-
-
```
```
---

refactor: :recycle: refactor navigation

---

src/pages/Consult/components/tabs/ConsultCard.tsx
src/pages/Survey/hooks/useCounselCardQuery.ts
src/pages/Survey/index.tsx

- 본 상담에서 진입한 경우 라우팅 다시 뒤로 보내주기
- 저장 실패시에도 라우팅되는 현상 버그 수정
- 쿼리 리팩토링(밸리데이션 에러도 에러 취급하여 false 반환)
- react router로 내비게이트 백 구현
- 없음
-
```
```
---

refactor: :recycle: refactor survey routing

---

src/components/NavigationRight.tsx
src/components/common/DataTable/table-cell.tsx
src/components/consult/Recording.tsx
src/components/table/TableCell.tsx
src/hooks/useRecording.ts
src/pages/Consult/components/recording/SelectSpeakerDialog.tsx
src/pages/Consult/hooks/query/counselRecording/useGetRecordingStatusQuery.ts
src/pages/Consult/index.tsx
src/pages/Home/index.tsx

- STT 리팩토링
- SNB 의 제어를 Consult 에서 분리시켰습니다
- 기디에서 그 툴팁 나오는 시간 200ms 로 다같이 줄여달래서 사용하는 곳 같이 반영했슴다
- 음슴
```
```
---

refactor: 🎨 Recording 관련 책임 분리

---

src/app/Routes.tsx
src/components/common/NavigationLeft.tsx

- 약사 내담자 관리 페이지 진입
- 라우터 변경
```
```
---

fix: :passport_control: allow user to access counselee page

---

src/hooks/useRecording.ts

- STT QA
- 녹음 저장 시 즉시 상태 변경 후 polling
- QA 하시는 분들을 위해 녹음한 파일 떨궈주는 테스트 코드 추가했습니다
- 음슴
```
```
---

fix: 🐛 저장 버튼 클릭 시, 지연 없이 status 변경

---

src/components/common/NavigationLeft.tsx

fix: ROLE_NONE 유저 홈 메뉴 표기

---

src/components/common/NavigationLeft.tsx
src/hooks/useRecording.ts
src/pages/Consult/components/CheckLeaveOutDialog.tsx
src/pages/Consult/components/FinishConsultDialog.tsx
src/pages/Consult/components/TemporarySaveDialog.tsx
src/pages/Consult/index.tsx
src/pages/Consult/types/Recording.enum.ts

- STT QA
- STT 임시저장 관련 기능 추가
- 없음
- 없음
```
```
---

feat: ✨ 본상담 녹음 중 다른 메뉴로 이탈 시 현재 녹음 파일 저장

---

src/components/common/DataTable/data-table.tsx
src/pages/Consult/components/table/MedicineRecordTable/medicineRecordTableColumns.tsx
src/pages/Session/components/table/CounselSessionColumns.tsx
src/utils/constants.ts
src/utils/inputValidations.ts

- [생년월일 잘못 입력시 백엔드 오류 출력](https://www.notion.so/yoonyounglee/1bf4b68481fb80639f03c2dabaec4d0d?pvs=4)
- [수정하기 및 삭제하기 클릭시 내역 화면이동](https://www.notion.so/yoonyounglee/1c54b68481fb80679a59efecd0ecd9ca?pvs=4)
- [의약품 ID 필수 버그](https://www.notion.so/yoonyounglee/ID-1bf4b68481fb80f2a648e089310057dd?pvs=4)
- [하루 한 끼 텍스트 변경](https://www.notion.so/yoonyounglee/1bf4b68481fb80a094e1d465ff4bbf10?pvs=4)
- [의약품 row 생성시 자동으로 상시복용 상태로 세팅](https://www.notion.so/yoonyounglee/1bf4b68481fb80559106d8b45614d709?pvs=4)
- data-table 리팩토링
- 의약품 테이블 리팩토링
- 없음
- 작업 겹쳤으면 미안해욤
```
- Comment 작성 시 Prefix로 P1, P2, P3, P4, P5 를 적어 주시면 Assignee가 보다 명확하게 …
```

fix: resolve several bugs

---

src/components/common/DataTable/medicine-search-cell.tsx
src/components/consult/HighlightInput.tsx
src/pages/Consult/components/table/PrevCounselTable/index.tsx
src/pages/Consult/components/tabs/PastConsult.tsx
src/pages/Consult/index.tsx

- Draft.js text 잘라내기 missing Node문제 수정
- 상담히스토리 조건수정, 바로가기 연결
-
-
-
```
```
---

fix: 본상담 중재기록 에디터 에러케이스 대응, 상담 히스토리 로직 수정

---

src/components/ui/datepicker.tsx
src/pages/Consult/hooks/useInitializeAllTabsData.ts

- 저장된 의약물 기록 삭제 직후 리스트가 업데이트 되지 않는 증상 해결
-
-
-
```
```
---

fix: 의약물 기록 삭제 query invalidate 미동작 수정

---

src/components/common/NavigationLeft.tsx
src/pages/Consult/index.tsx

- [페이지 이탈 시 dialog 추가](https://www.notion.so/yoonyounglee/1874b68481fb80869782c4da436d7288?pvs=4)
- 상담 완료 상태 아닌 경우 dialog 띄우기
- 없음
- 업음
```
- P4: …
```

feat: ✨ 상담 진행 중 상태에서 이탈 시, 임시저장 기능 추가

---

src/pages/Session/components/SessionDeleteDialog.tsx
src/pages/Session/components/table/CounselSessionColumns.tsx

- 상담 삭제 dialog 추가 및 페이지 이동 방지 [상담 삭제 시 확인 팝업이 떠야함](https://www.notion.so/yoonyounglee/1be4b68481fb80ca8dc4d5bd6c3a9ca8?pvs=4)
-
-
-
```
- P4: 반영해도 …
```

feat: 상담삭제 dialog 추가

---

src/components/common/NavigationLeft.tsx
src/pages/Consult/components/tabs/PastConsult.tsx

-  상담 히스토리 상담내용 요약 AI 요약으로 변경
-  LNB 기초상담 진행중인 상담 LNB 미동작 방지 
-
-
-
```
```
---

fix: 상담 히스토리 상담내용 요약 AI 요약으로 변경

---

package.json
pnpm-lock.yaml

- https://github.com/MediBird/caring-note-web/security/dependabot/12 [Moderate](https://github.com/MediBird/caring-note-web/security/dependabot?q=is%3Aopen+severity%3Amoderate) [Direct](https://github.com/MediBird/caring-note-web/security/dependabot?q=is%3Aopen+relationship%3Adirect)
#12 opened 10 hours ago • Detected in vite (npm) • pnpm-lock.yaml
- https://github.com/MediBird/caring-note-web/security/dependabot/11 [Moderate](https://github.com/MediBird/caring-note-web/security/dependabot?q=is%3Aopen+severity%3Amoderate) [Direct](https://github.com/MediBird/caring-note-web/security/dependabot?q=is%3Aopen+relationship%3Adirect)
- vite update
- 없음
- https://github.com/MediBird/caring-note-web/security/dependabot/13 [Low](https://github.com/MediBird/caring-note-web/security/dependabot?q=is%3 …

fix: :arrow_up: update vite version due to vulnerability

---

src/api/models/allergy-dto.ts
src/api/models/medication-side-effect-dto.ts
src/pages/Survey/components/tabs/HealthInfo.tsx
src/pages/Survey/components/tabs/LivingInfo.tsx

- [선택값 기본 및 선택값 취소 불가능](https://www.notion.so/yoonyounglee/default-1c74b68481fb80339129e84edea2accb?pvs=4)
- Button group null값 허용
- 없음
-
```
```
---

fix: :recycle: enable boolean button to be null

---

src/pages/Consult/components/tabs/PastConsult.tsx

- 이전 상담내역 비어있을시 하이라이트 파싱 에러 발생
-
-
-
```
```
---

hotfix: :bug 상담기록 하이라이트 파싱 수정

---

package.json
pnpm-lock.yaml
src/pages/Counselee/components/dialog/CounseleeDialog.tsx
src/utils/inputValidations.ts

feat: :sparkles: add libphonenumber-js

---

src/pages/Counselee/hooks/query/useCounseleeQuery.ts

- 피그마랑 토스트 메세지가 달라서 해결해달라고 하셨습니다.
- 토스트 문구 바꿨어요.
-
-
```
```
---

fix: :pencil2: fix toast typos

---

src/components/consult/HighlightInput.tsx
src/pages/Consult/hooks/useInitializeAllTabsData.ts
src/utils/parseEditorContent.ts

- 중재기록 상태 업데이트 버그 수정
- 상담을 변경해도 이전 상담의 중재기록에서 변경되지 않는 문제 수정
- [재상담 > 중재기록 작성 진입 시 예전에 적은 중재기록 내용이 노출됨](https://www.notion.so/yoonyounglee/1d04b68481fb80339f95d71a5a556b3e?pvs=4)
- [중재기록 작성에서 다른 내담자의 중재기록 작성내용이 노출됨](https://www.notion.so/yoonyounglee/1d04b68481fb807c9a3acea8c345a1f4?pvs=4)
-
-
```
- …
```

fix: 🐛 중재기록 상태 업데이트 버그 수정

---

src/pages/Counselee/components/dialog/CounseleeDialog.tsx

- 행정동 힌트 텍스트 문구 상이함
- 플레이스 홀더 행정동 -> OO동
- 없음
- 없음
```
```
---

fix: modify hint text of district placeholder in counselee dialog

---

README.md

- readme에  lefthook관련 내용을 추가했습니다.
- 없음
- 없음
- 
```
```
---

docs: :memo: 프로젝트 readme lefthook 내용 추가

---

.env
.github/workflows/auto-pr-from-staging.yml
.github/workflows/deployment-main.yml
.github/workflows/deployment-staging.yml
.github/workflows/pr-branch-rule-check.yml
src/app/keycloak.ts

- keycloak client id의 유동적 사용
- staging 환경을 위한 git actions 도입
- 스테이징에서 자동 pr 생성
- 브랜치 전략 점검 깃 액션
- 배포 방식 변경
- 없음
-
```
```
---

feat: 👷 add git action for staging environment

---

.github/workflows/deployment-main.yml
.github/workflows/deployment-staging.yml
Dockerfile

- ci cd 오류 해결
- 저의 지능의 문제점을 확인했습니다.
- 없음
-
```
```
---

fix: :green_heart: fix ci build

---

.github/workflows/auto-pr-from-staging.yml
.github/workflows/deployment-staging.yml
package.json

fix: :green_heart: modify deployment action files (check out misssing)

---

.github/workflows/deployment-main.yml

fix: main 배포 스크립트에서 네임스페이스를 'caring-note'에서 'default'로 변경

---

.env
.gitignore

- .env 파일이 ignore되어있지 않아 staging환경과 main 환경 전환시 env를 수정해야함
- .env 파일 gitignore 설정 추가
-
-
```
```
---

chore: .env 파일 삭제 및 .gitignore에 .env 관련 항목 추가

---

package.json
pnpm-lock.yaml

chore: :fire: remove redux package

---

src/pages/Consult/components/ConsultHeader.tsx
src/pages/Consult/components/dialog/FinishConsultDialog.tsx
src/pages/Consult/hooks/query/medicationRecord/useMedicationRecordSave.tsx
src/pages/Consult/hooks/query/useMedicineConsultQuery.ts
src/pages/Consult/hooks/query/wasteMedicineRecord/useSaveWasteMedication.ts
src/pages/Consult/hooks/query/wasteMedicineRecord/useWasteMedicationMutate.tsx
src/pages/Consult/index.tsx

- 본상담 상담완료시 저장 실패하면 Navigate 방지 관련 상담완료 저장동작 분기처리 개선[https://www.notion.so/yoonyounglee/Navigate-1c54b68481fb809782eef6b9b5774edc?pvs=4](url)
- 본상담 저장 에러 핸들링 코드 추가
- 본상담 헤더 컴포넌트 분리코드 재적용
- 없음
-
```
- P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 …
```

refactor: ✨ 상담 완료 저장결과에 따른 분기처리 개선

---

src/pages/Home/components/ConsultCount.tsx
src/pages/Home/components/MeaningfulStatistics.tsx

- 네비바+홈화면 통계 ‘케어링 메시지’ 제외 처리 마무리
-
-
-
```
```
---

feat: ✨ 상담 통계 컴포넌트에 함께한 사람 통계 카드 추가

---

package.json
pnpm-lock.yaml
src/components/magicui/marquee.tsx
src/components/magicui/testimonial.tsx
src/index.css
src/pages/Home/components/CollegeMessages.tsx
tailwind.config.js

- 동료약사들의 따뜻한 마음 구현
- 마르퀴 추가
- Testimonial 추가
- 애니메이션 추가
- 없음
-
```
```
---

feat: ✨ 마르퀴 컴포넌트 및 추천사 카드 추가, 패키지 의존성 업데이트

---

src/pages/Session/components/table/CounselSessionColumns.tsx

- 취소 회차 상담 회차 및 약사 "-" 처리
- CounselSessionColumns 변경
```
```
---

feat: ✨ 상담 회차 및 상담사 이름 표시 로직 수정, 취소된 세션에 대한 처리 추가

---

src/components/common/ContentCard.tsx
src/components/common/SectionContainer.tsx
src/pages/Consult/components/sections/CounselPurposeSection.tsx
src/pages/Consult/components/sections/HealthInfoSection.tsx
src/pages/Consult/components/sections/IndependentLifeSection.tsx
src/pages/Consult/components/sections/LivingInfoSection.tsx
src/pages/Consult/components/tabs/ConsultCard.tsx
src/pages/Consult/components/tabs/PastConsult.tsx

- 기초 상담 리뉴얼 0.5차 진행
- 기존 컨설트 카드 코드 삭제
- 신규 컴포넌트 생성
- 없음
```
```
---

feat: 새로운 상담 섹션 컴포넌트 추가 및 기존 ConsultCard 리팩토링

---

src/components/common/Footer.tsx
src/pages/Consult/components/interventionEditor/index.tsx
src/pages/Consult/components/interventionEditor/useInterventionEditor.ts
src/pages/Consult/hooks/query/useMedicineConsultQuery.ts
src/pages/Consult/index.tsx
src/pages/Layout.tsx
src/pages/Session/utils/dateTimeUtils.tsx
src/pages/Survey/index.tsx

- 중재기록 local 저장 timstamp 추가
- footer 레이아웃 수정
- 에디터 저장 분기 로직 수정
- 기초설문 헤더 레이아웃 수정
-
-
```
```
---

feat: 중재기록 저장 timstamp 추가

---

src/pages/Consult/components/tabs/PastConsult.tsx
src/pages/Consult/components/tabs/components/RecordCard.tsx
src/pages/Consult/components/tabs/components/SessionHeader.tsx
src/utils/getMarkdownFromLexical.ts

- 상담 히스토리 중재기록 카드 lexcial to markdown 유틸함수 적용
- getMarkdownFromLexical 함수 추가
- RecordCard 적용
-
-
```
```
---

feat: :sparkles: 상담 히스토리 중재기록 카드 lexcial to markdown 유틸함수 적용

---

src/pages/Consult/components/TabContents.tsx
src/pages/Consult/components/sections/LivingInfoSection.tsx
src/pages/Consult/components/tabs/ConsultCard.tsx
src/pages/Consult/hooks/store/useRecordingStore.ts
src/pages/Consult/index.tsx

- 녹음 다이얼로그 표시 조건 로직 최적화
- LivingInfoSection에서 아이템 레이아웃 개선
- ConsultCard에서 반응형 디자인 적용
- useRecordingStore에서 세션 로드 로직 간소화
-
-
-
-
```
- P4: 반영해도 좋고 …
```

feat: 상담 페이지 UI 및 상태 관리 개선

---

src/api/models/counsel-session-stat-res.ts
src/pages/Home/components/MeaningfulStatistics.tsx

- CounselSessionStatRes 인터페이스의 필드 이름 변경: totalSessionCount, totalCaringMessageCount, counselHoursForThisMonth를 각각 counselHoursThisMonth, medicationCounselCountThisYear, counselorCountThisYear로 수정
- MeaningfulStatistics 컴포넌트에서 해당 필드에 맞춰 데이터 참조 수정
-
-
-
-
```
- P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 …
```

feat: 상담 세션 통계 인터페이스 및 통계 컴포넌트 수정
